#ifndef _OBLIVION_LIMITS_H_
#define _OBLIVION_LIMITS_H_

#define MAX_SPHERES 10
#define MAX_LINES 300
#define MAX_LIGHTS 10

#define MODEL_PRIMITIVE_TYPE 1
#define SCENE_PRIMITIVE_TYPE 2

#define MAX_TEXTURE_COLUMNS 16384
#define MAX_TEXTURES_IN_TEXTURE_ARRAY 2048

#endif // _OBLIVION_LIMITS_H_
